### ISSUE TITLE
web issues

### ISSUE THREAD

**Issue by CripyIce** [Dana-Ferguson/time_machine#40]
Hi there,
Trying to use this library with `flutter web` but I have some issues with it:
<img width="485" alt="time_machine1" src="https://user-images.githubusercontent.com/26387823/93923836-980b2400-fd1c-11ea-9f08-6584294e432c.png">
1. I don't have this file anywhere in my project - I've looked in the open issues and saw that other people have those files.
2. The get request tries to get the file from the root of the domain instead of the root of the web project which is:`https://mydoamin.com/ironclic/`.

This is my configuration:
flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale
    en-IL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.1)
[✓] Connected device (2 available)
```

pubspec.yaml:
```yaml
dependencies:
  time_machine: ^0.9.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icon/
    - assets/translations/
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
```

`build/web` structure:
![image](https://user-images.githubusercontent.com/26387823/93924594-a0179380-fd1d-11ea-9eeb-52529a939d20.png)

Thanks for the help!
