### ISSUE TITLE
Compile error with latest version of meta.

### ISSUE THREAD

**Issue by mstich-triva** [Dana-Ferguson/time_machine#44]
Upgraded to latest version of flutter and now get a compile error:  

calendar_system.dart:8:2: Error: 'internal' is imported from both 'package:meta/meta.dart' and 'package:time_machine/src/time_machine_internal.dart'.

zoneddatetime.dart:18:2: Error: 'internal' is imported from both 'package:meta/meta.dart' and 'package:time_machine/src/time_machine_internal.dart'.

**Comment by IoanaAlexandru** [comment]
A temporary fix is to override the `meta` package dependency in your `pubspec.yaml` file:

```
dependency_overrides:
  meta: 1.3.0-nullsafety.3
```

**Comment by mstich-triva** [comment]
> A temporary fix is to override the `meta` package dependency in your `pubspec.yaml` file:
> 
> ```
> dependency_overrides:
>   meta: 1.3.0-nullsafety.3
> ```

Thank you for this.

**Comment by micimize** [comment]
The override didn't work for me so for now I just did
```bash
cd ~/.pub-cache/hosted/pub.dartlang.org/time_machine-0.9.15/lib
sed -i '' 's/@internal//g' src/*/*/*
sed -i '' 's/@internal//g' src/*/*.dart
sed -i '' 's/@internal//g' src/*.dart
sed -i '' 's/@internal//g' *.dart
```

**Comment by jallynme** [comment]
I think force dependency overrides may break other package

**Comment by rich-j** [comment]
Another temporary fix is to directly specify pull request #47 (thanks @IoanaAlexandru) that provides one possible fix. Change `pubspec.yaml` time_machine dependency to:

```yaml
  #  time_machine: ^0.9.15
  time_machine:
    git:
      url: https://github.com/Dana-Ferguson/time_machine
      ref: 7753e0d
```

Remove the `dependency_override` on `meta` if you previously added it.

**Comment by AnasMasri** [comment]
> Another temporary fix is to directly specify pull request #47 (thanks @IoanaAlexandru) that provides one possible fix. Change `pubspec.yaml` time_machine dependency to:
> 
> ```yaml
>   #  time_machine: ^0.9.15
>   time_machine:
>     git:
>       url: https://github.com/Dana-Ferguson/time_machine
>       ref: 7753e0d
> ```
> 
> Remove the `dependency_override` on `meta` if you previously added it.

This is also very helpful if you're using [timetable](https://github.com/JonasWanke/timetable) on Flutter 1.22.4 where you have to use _only_ `timetable` v `0.2.8 ` dependency (no need to explicitly depend on time_machine which timetable depends on it), then add this to pubspec: 
```

dependency_overrides:
  time_machine:
    git:
      url: https://github.com/Dana-Ferguson/time_machine
      ref: 7753e0d

```
