### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by Vipulkerai** [Dana-Ferguson/time_machine#61]
This is a request to add support for null safety to this package. See the migration guide for details about enabling null safety.

**Comment by SteveAlexander** [comment]
Hi @Vipulkerai 

The code in this repo is already null safe.

I guess what you're asking for is a new release to pub.dev ?

@Dana-Ferguson do you have time to do a release sometime soon?

**Comment by hizmarck** [comment]
@Vipulkerai if you have a problem with null safety migration you can use this while they releasing on pub.dev 

```
time_machine:
    git:
      url: https://github.com/Dana-Ferguson/time_machine
      ref: master
```
