### ISSUE TITLE
Exception: Pass in the rootBundle from 'package:flutter/services.dart';

### ISSUE THREAD

**Issue by pedzed** [Dana-Ferguson/time_machine#7]
I was looking at [the Time Machine docs](https://pub.dartlang.org/documentation/time_machine) as well as the given example and this is my code:

```dart
Future<void> main() async {
  setUp();
  runApp(new App());
}

Future<void> setUp() async {
  print('TimeZone!');
  
  await TimeMachine.initialize({
    rootBundle: rootBundle,
  });

  print("Hello, ${DateTimeZone.local} from the Dart Time Machine!\n");
  var tzdb = await DateTimeZoneProviders.tzdb;
  var timeZoneAmsterdam = await tzdb['Europe/Amsterdam'];
}
```

But I am getting this error:
>Exception has occurred.
>Exception: Pass in the rootBundle from 'package:flutter/services.dart';

Even though I have added this:
```dart
import 'package:flutter/services.dart';
```

My `pubspec.yaml` (minus the unnecessary):
```yaml
dependencies:
  flutter:
    sdk: flutter
  time_machine: ^0.9.4

flutter:
  assets:
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
```
Is there a bug or is it just me?
```bash
$ flutter --version
Flutter 0.5.8 • channel dev • https://github.com/flutter/flutter.git
Framework • revision e4b989bf3d (8 days ago) • 2018-08-09 09:45:44 -0700
Engine • revision 3777931801
Tools • Dart 2.0.0-dev.69.5.flutter-eab492385c
```
